# Example configuration file for Legacy Mode
# This demonstrates how to define explicit protein-ligand pairs for MD simulations

[mode]
type = "legacy"  # Use "legacy" mode for explicit protein-ligand pairs

# Legacy mode settings - explicitly define protein-ligand pairs
# Each key will be used as the work directory for simulation outputs
[legacy.runs]
# Format: RunName = { protein = "path/to/protein.pdb", ligand = "path/to/ligand.sdf" }
Run1 = { protein = "./Proteins/protein1.pdb", ligand = "./Ligands/ligand1.sdf" }
Run2 = { protein = "./Proteins/protein2.pdb", ligand = "./Ligands/ligand2.sdf" }
# For protein-only simulation, use ligand = "APO"
Run3 = { protein = "./Proteins/protein3.pdb", ligand = "APO" }

# General simulation parameters
[system]
delta_pico = 0.002
rerun = false

# Parameters for NVT equilibration step
[nvt]
steps = 400
dcd_save = 50
log_save = 1
# List of temperatures
temps_list = [50, 100, 150, 200, 250, 300, 301]

# Parameters for NPT equilibration step
[npt]
steps = 400
dcd_save = 50
log_save = 1
# List of restraint values
rests_list = [1000000000, 100000, 1000, 100, 10, 1]
# Atoms to apply restraints to
atoms_to_restraints = ["CA"]

# Parameters for production MD step
[md]
steps = 150000
dcd_save = 100
log_save = 10 